function [fitresult, gof] = createFitBCNT(LBD, Pro, BcnVet)
%CREATEFIT(LBD,PRO,BCNVET)
%  Create a fit.
%
%  Data for 'AjusteBcnt' fit:
%      X Input : LBD
%      Y Input : Pro
%      Z Output: BcnVet
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Feb-2015 20:38:37


%% Fit: 'AjusteBcnt'.
[xData, yData, zData] = prepareSurfaceData( LBD, Pro, BcnVet );

% Set up fittype and options.
% ft = fittype( 'poly45' );

ft = fittype( 'poly45' );


% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft)%, 'Normalize', 'on' );

Coeficientes = coeffvalues(fitresult)

% Create a figure for the plots.
figure( 'Name', 'AjusteBcnt' );

% Plot fit with data.
subplot( 2, 2, 2 );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'AjusteBcnt', 'BcnVet vs. LBD, Pro', 'Location', 'NorthEast' );
% Label axes
xlabel LBD
ylabel Pro
zlabel BcnVet
grid on
view( 162.0, 32.0 );

% Plot residuals.
subplot( 2, 2, 4 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'AjusteBcnt - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel LBD
ylabel Pro
zlabel BcnVet
grid on
view( 162.0, 32.0 );

% Make contour plot.
subplot( 1, 2, 1 );
h = plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
legend( h, 'AjusteBcnt', 'BcnVet vs. LBD, Pro', 'Location', 'NorthEast' );
% Label axes
xlabel LBD
ylabel Pro
grid on


